// ═══════════════════════════════════════════════════════════
//  data.js — JSON de productos y categorías
// ═══════════════════════════════════════════════════════════

export const categoriesData = [
  { value: 'all',        label: 'Todos' },
  { value: 'ropa',       label: 'Ropa' },
  { value: 'accesorios', label: 'Accesorios' },
  { value: 'calzado',    label: 'Calzado' },
  { value: 'bolsos',     label: 'Bolsos' },
]

export const productsData = [
  {
    id: 1, name: 'Blazer Oversize Noir', brand: 'NOIRE STUDIO',
    category: 'ropa', emoji: '🧥',
    price: 289000, discount: 0, stock: 8, rating: 5,
    isNew: true, featured: true,
    colors: ['#1a1a1a','#3d2b1f','#2b2b3d'],
    selectedColor: 0,
    bgColor: '#141414',
  },
  {
    id: 2, name: 'Trench Coat Slim', brand: 'ATELIER M',
    category: 'ropa', emoji: '🧣',
    price: 420000, discount: 20, stock: 3, rating: 4,
    isNew: false, featured: false,
    colors: ['#c8a97e','#6b5a3e','#f0ebe3'],
    selectedColor: 0,
    bgColor: '#141410',
  },
  {
    id: 3, name: 'Pantalón Palazzo', brand: 'NOIRE STUDIO',
    category: 'ropa', emoji: '👖',
    price: 175000, discount: 0, stock: 12, rating: 4,
    isNew: true, featured: false,
    colors: ['#1a1a1a','#555555','#f0ebe3'],
    selectedColor: 0,
    bgColor: '#111116',
  },
  {
    id: 4, name: 'Camiseta Oversize', brand: 'BASICS CO',
    category: 'ropa', emoji: '👕',
    price: 89000, discount: 15, stock: 20, rating: 3,
    isNew: false, featured: false,
    colors: ['#ffffff','#1a1a1a','#c8a97e'],
    selectedColor: 0,
    bgColor: '#131313',
  },
  {
    id: 5, name: 'Vestido Asimétrico', brand: 'NOIRE STUDIO',
    category: 'ropa', emoji: '👗',
    price: 340000, discount: 0, stock: 5, rating: 5,
    isNew: true, featured: false,
    colors: ['#1a1a1a','#3d2b1f'],
    selectedColor: 0,
    bgColor: '#0e0e12',
  },
  {
    id: 6, name: 'Reloj Minimal Noir', brand: 'CHRONO LAB',
    category: 'accesorios', emoji: '⌚',
    price: 580000, discount: 0, stock: 4, rating: 5,
    isNew: true, featured: false,
    colors: ['#1a1a1a','#c8a97e','#f0ebe3'],
    selectedColor: 0,
    bgColor: '#100e0e',
  },
  {
    id: 7, name: 'Cinturón Cuero Fino', brand: 'ATELIER M',
    category: 'accesorios', emoji: '🪢',
    price: 125000, discount: 10, stock: 9, rating: 4,
    isNew: false, featured: false,
    colors: ['#1a1a1a','#6b5a3e'],
    selectedColor: 0,
    bgColor: '#110f0a',
  },
  {
    id: 8, name: 'Gafas Ovaladas', brand: 'LENS NOIR',
    category: 'accesorios', emoji: '🕶️',
    price: 210000, discount: 0, stock: 0, rating: 4,
    isNew: false, featured: false,
    colors: ['#1a1a1a','#c8a97e'],
    selectedColor: 0,
    bgColor: '#0e0e0e',
  },
  {
    id: 9, name: 'Collar Geométrico', brand: 'METL CO',
    category: 'accesorios', emoji: '📿',
    price: 98000, discount: 0, stock: 15, rating: 3,
    isNew: true, featured: false,
    colors: ['#c8a97e','#c0c0c0','#1a1a1a'],
    selectedColor: 0,
    bgColor: '#0d0d0d',
  },
  {
    id: 10, name: 'Chelsea Boot Mate', brand: 'SOLE NOIR',
    category: 'calzado', emoji: '👢',
    price: 460000, discount: 0, stock: 6, rating: 5,
    isNew: true, featured: false,
    colors: ['#1a1a1a','#6b5a3e'],
    selectedColor: 0,
    bgColor: '#0e0a0a',
  },
  {
    id: 11, name: 'Sneaker Platform', brand: 'ABOVE AVG',
    category: 'calzado', emoji: '👟',
    price: 295000, discount: 25, stock: 8, rating: 4,
    isNew: false, featured: false,
    colors: ['#f0ebe3','#1a1a1a','#c8a97e'],
    selectedColor: 0,
    bgColor: '#131313',
  },
  {
    id: 12, name: 'Loafer Cuero Pulido', brand: 'SOLE NOIR',
    category: 'calzado', emoji: '🥿',
    price: 390000, discount: 0, stock: 4, rating: 4,
    isNew: false, featured: false,
    colors: ['#1a1a1a','#6b5a3e','#c8a97e'],
    selectedColor: 0,
    bgColor: '#0d0a08',
  },
  {
    id: 13, name: 'Tote Bag Estructurado', brand: 'CARRY CO',
    category: 'bolsos', emoji: '👜',
    price: 320000, discount: 0, stock: 7, rating: 5,
    isNew: true, featured: false,
    colors: ['#1a1a1a','#c8a97e','#f0ebe3'],
    selectedColor: 0,
    bgColor: '#0e0c0a',
  },
  {
    id: 14, name: 'Mini Bag Cadena', brand: 'CARRY CO',
    category: 'bolsos', emoji: '👛',
    price: 230000, discount: 10, stock: 3, rating: 4,
    isNew: false, featured: false,
    colors: ['#c8a97e','#1a1a1a'],
    selectedColor: 0,
    bgColor: '#100e08',
  },
]
